---
# Bacchus installer parameters file
#
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# !!! DO NOT FORGET TO CHANGE THE DEFAULT PASSWORDS !!!!
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#
# Please note that ansible playbook can be run more than once, each time you run the playbook
# it will change the settings to these defaults.
#
# The scripts under {bacchus_base_path}/tools are also based on these parameters. 
# If you change the following credentials manually on the corresponding application, 
# you may need to edit the scripts in tools directory.
#
# Genereal settings
#
bacchus_hostname: bacchus.local.net
bacchus_base_path: /opt/bacchus
timezone: Europe/Istanbul
#
#Inventory job interval, default 10 mins
inv_sched_interval: 10
#
# Snapshot persist memory setting:
# when enabled all backups will include memory state
# this option may lead performance issues, use carefully
snapshot_persist_memory: False
#
# MariaDB credentials
#
bacchus_db_user: bacchus
bacchus_db_pass: 123qwe
#
# RabbitMQ credentials
# 
bacchus_mq_user: bacchus
bacchus_mq_pass: qwe123
#
#
# Celery settings
#
flower_user: admin
flower_pass: admin
worker_concurrency: 16
#
#
# Bacchus Web Console settings
#
admin_username: admin
admin_password: 123qwe
admin_email: admin@localhost
session_cookie_age: 300
bacchus_bind_port: 8080
nginx_ssl_port: 8081
#
# E-mail settings
# 
# If TLS is disabled in your setup, change "email_port" to 25 and "email_use_tls" to False
#
email_host: smtphost
email_host_user: myusername@smtphost
email_host_password: mysecret
email_port: 587
email_use_tls: True
#
#