---
- name: Install OpenBacchus
  hosts: "{{bacchus_hostname}}"
  become: true
  become_method: sudo
  vars_files: default.yml    

  tasks:

   - name: Include a play after another play
     include: "{{ role_path }}"/tasks/main.yml