---
# tasks/Ubuntu/main.yml: Ubuntu specific set-up
# This takes care of base prerequisites for Ubuntu

- include_vars: "main.yml"

- name: apt => install dependencies
  apt: name={{item}} state=installed
  with_items:
    - software-properties-common
    - gcc
    - make
    - python-dev
    - libxml2-dev
    - libmariadbclient-dev
    - libmariadbd-dev
    - libcurl4-openssl-dev 
    - libssl-dev
    - python-semanage
    - git
    - python-pip
  update_cache: yes

- name: apt => install MariaDB 
  apt:
   name: mariadb-server
   state: installed

- name: apt => install RabbitMQ
  apt:
   name: rabbitmq-server
   state: installed

- name: apt => install NGINX
  apt:
   name: nginx
   state: installed

- name: upgrade => pip
  command: pip install --upgrade pip

- name: pip => install wheel
  pip:
   name: wheel 
   
- name: pip => install django
  pip:
   name: django
   version: 1.10.6

- name: pip => install built-in encyrption
  pip:
   name: django-fernet-fields

- name: pip => install Ovirt Engine SDK
  pip:
   name: ovirt-engine-sdk-python
   version: 4.1.2

- name:  pip => install Python MySQL support
  pip:
   name: MySQL-python

- name: pip => install Celery
  pip:
   name: celery
   version: 4.0.2

- name: pip => install Celery Beat
  pip:
   name: django-celery-beat

- name: pip => install Celery Results
  pip:
   name: django-celery-results

- name: pip => install Flower
  pip:
   name: flower

